{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .views import ShowHomeView, SaveTheDateView, ConfirmacaoRedirectView
from .forms import LoginForm


urlpatterns = patterns('',  # noqa

    url(r'^confirmacao/$', ConfirmacaoRedirectView.as_view(),
        name='core.confirmacao'),
    url(r'^confirmacao$',
        ConfirmacaoRedirectView.as_view(),),

    url(r'^$', ShowHomeView.as_view(),
        name='core.showhome'),

    url(r'^save-the-date/$',
        SaveTheDateView.as_view(), name='core.savethedate'),

    url(r'^dicasdehoteis/$',
        TemplateView.as_view(template_name="core/dicasdehoteis.html"),
        name='core.dicasdehoteis'),

    url(r'^apps/$',
        TemplateView.as_view(template_name="core/apps.html"),
        name='core.apps'),

    url(r'^agradecimentopresente/$',
        TemplateView.as_view(template_name="core/agradecimento_presente.html"),
        name='core.agradecimentopresente'),

    url(r'^cerimoniareligiosa/$',
        TemplateView.as_view(template_name="core/cerimoniareligiosa.html"),
        name='core.cerimoniareligiosa'),

    url(r'^salaodebeleza/$',
        TemplateView.as_view(template_name="core/salaodebeleza.html"),
        name='core.salaodebeleza'),

    url(r'^restaurante/$',
        TemplateView.as_view(template_name="core/restaurante.html"),
        name='core.restaurante'),

    url(r'^avisoconfirmacao/$',
        TemplateView.as_view(template_name="core/avisoconfirmacao.html"),
        name='core.avisoconfirmacao'),

    # login
    url(r'^auth/$',
        auth_views.login, {'template_name': 'core/login.html',
                           'authentication_form': LoginForm},
        name='url_login_auth'),

)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import (ConfirmacaoHomeView, ConfirmacaoUpdateView,
                    ConfirmacaoAcompanhanteCreateView,
                    ConfirmacaoAcompanhanteDeleteView,
                    ListaConvidadosListView,
                    ConvidadoRSVPUpdateView,
                    ConvidadoUpdateView, AcompanhanteUpdateView, )


urlpatterns = patterns('',  # noqa

    url(r'^confirmacao/$',
        ConfirmacaoHomeView.as_view(),
        name='rsvp.confirmacaohome'),

    url(r'^confirmacao/update/(?P<pk>\d+)-(?P<slug>[\w-]+)/$',
        ConfirmacaoUpdateView.as_view(),
        name='rsvp.confirmacao.update'),

    url(r'^confirmado/$',
        TemplateView.as_view(template_name="rsvp/confirmado.html"),
        name='rsvp.confirmado'),

    url(r'^confirmacao/acompanhante/create/(?P<convidado_pk>\d+)/$',
        ConfirmacaoAcompanhanteCreateView.as_view(),
        name='rsvp.confirmacao.convidado.create'),

    url(r'^confirmacao/acompanhante/delete/(?P<pk>\d+)/(?P<convidado_pk>\d+)/$',
        ConfirmacaoAcompanhanteDeleteView.as_view(),
        name='rsvp.confirmacao.convidado.delete'),

    # lista admin
    url(r'^lista/convidados/$',
        ListaConvidadosListView.as_view(),
        name='rsvp.lista.convidados.list'),

    url(r'^lista/convidados/rsvp/update/(?P<pk>\d+)/$',
        ConvidadoRSVPUpdateView.as_view(),
        name='rsvp.convidadorsvp.update'),

    url(r'^lista/convidados/update/(?P<pk>\d+)/$',
        ConvidadoUpdateView.as_view(),
        name='rsvp.convidado.update'),

    url(r'^lista/acompanhante/update/(?P<pk>\d+)/$',
        AcompanhanteUpdateView.as_view(),
        name='rsvp.acompanhante.update'),
)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.utils.crypto import get_random_string
from django.core.urlresolvers import reverse

from model_utils import Choices

RSVP = Choices(('vazio', _(' ? ')),
               ('sim', _('Sim')),
               ('nao', _('Não')), )

TIPO_ACOMPANHANTE = Choices(('adulto', _('Adulto')),
                            ('ate_8', _('Até 8 anos')), )


class ConvidadoRSVP(models.Model):
    slug = models.SlugField(max_length=128,
                            blank=True, default=get_random_string)
    data = models.DateTimeField(_('data'), auto_now_add=True)
    rsvp = models.CharField('Confirma presença?',
                            choices=RSVP, default=RSVP.vazio,
                            max_length=16)
    nome_completo = models.CharField('nome completo', max_length=128)
    email = models.EmailField('e-mail', max_length=128, default='', blank=True)
    fone = models.CharField('fone', max_length=32, default='', blank=True)
    eh_primeiro_acesso = models.BooleanField(default=True)
    contabilizado = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Convidado RSVP")
        verbose_name_plural = _("Convidados (RSVP)")

    def __str__(self):
        return "{0} --> {1}".format(self.nome_completo, self.rsvp)

    def get_absolute_url(self):
        return reverse('rsvp.confirmacao.update',
                       kwargs={'pk': self.id, 'slug': self.slug, })

    @property
    def acompanhate_list(self):
        return AcompanhanteRSVP.objects.filter(convidado_rsvp=self)


class AcompanhanteRSVP(models.Model):
    convidado_rsvp = models.ForeignKey(ConvidadoRSVP,
                                       verbose_name=_('convidado'),
                                       related_name='acompanhantes')
    nome = models.CharField('nome', max_length=128)
    tipo = models.CharField('selecione', choices=TIPO_ACOMPANHANTE,
                            default=TIPO_ACOMPANHANTE.adulto,
                            max_length=16)

    class Meta:
        verbose_name = _("Acompanhante RSVP")
        verbose_name_plural = _("Acompanhantes (RSVP)")
        ordering = ('nome', )

    def __str__(self):
        return self.nome

    @property
    def tipo_verbose(self):
        return TIPO_ACOMPANHANTE[self.tipo]


class Convidado(models.Model):
    GRUPOS = Choices(('Noivo.ParteDaMae', _('Noivo - Parte da Mãe')),
                     ('Noivo.ParteDoPai', _('Noivo - Parte do Pai')),
                     ('Noivo.Amigos', _('Noivo - Amigos')),
                     ('Noiva.ParteDaMae', _('Noiva - Parte da Mãe')),
                     ('Noiva.ParteDoPai', _('Noiva - Parte do Pai')),
                     ('Noiva.Amigos', _('Noiva - Amigos')), )
    grupo = models.CharField('Grupo', default='geral', max_length=32,
                             choices=GRUPOS)
    data = models.DateTimeField(_('data'), auto_now_add=True)
    rsvp = models.CharField('Confirma presença?',
                            choices=RSVP, default=RSVP.vazio,
                            max_length=16)
    nome_completo = models.CharField('nome completo', max_length=128)
    email = models.EmailField('e-mail', max_length=128, default='', blank=True)
    fone = models.CharField('fone', max_length=32, default='', blank=True)

    class Meta:
        verbose_name = _("Lista Convidado")
        verbose_name_plural = _("Lista Convidados")

    def __unicode__(self):
        return "{0} --> {1}".format(self.nome_completo, self.rsvp)

    @property
    def acompanhate_list(self):
        return Acompanhante.objects.filter(convidado=self)

    def get_absolute_url(self):
        return reverse('rsvp.listaconvidado.update', kwargs={'pk': self.id, })

    @property
    def confirmado(self):
        return self.rsvp == RSVP.sim

    @property
    def nao_confirmado(self):
        return self.rsvp == RSVP.nao


class Acompanhante(models.Model):
    convidado = models.ForeignKey(Convidado,
                                  verbose_name=_('convidado'),
                                  related_name='acompanhantes')
    rsvp = models.CharField('Confirma presença?',
                            choices=RSVP, default=RSVP.vazio,
                            max_length=16)
    nome = models.CharField('nome', max_length=128)
    tipo = models.CharField('selecione', choices=TIPO_ACOMPANHANTE,
                            default=TIPO_ACOMPANHANTE.adulto,
                            max_length=16)

    class Meta:
        verbose_name = _("Acompanhante")
        verbose_name_plural = _("Acompanhantes")
        ordering = ('nome', )

    def __unicode__(self):
        return self.nome

    @property
    def tipo_verbose(self):
        return TIPO_ACOMPANHANTE[self.tipo]

    @property
    def confirmado(self):
        return self.rsvp == RSVP.sim

    @property
    def nao_confirmado(self):
        return self.rsvp == RSVP.nao

    @property
    def adulto(self):
        return self.tipo == TIPO_ACOMPANHANTE.adulto

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.core.mail import send_mail
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils import timezone

from braces import views

from .models import (ConvidadoRSVP, AcompanhanteRSVP,
                     Convidado, Acompanhante, RSVP, TIPO_ACOMPANHANTE, )
from .forms import (ConfirmacaoHomeForm, ConvidadoRSVPForm,
                    AcompanhanteRSVPForm, ListaConvidadoRSVPForm,
                    ListaConvidadoForm, ListaAcompanhanteForm, )
from .validators import phone_validator


class ConfirmacaoHomeView(FormView):
    form_class = ConfirmacaoHomeForm
    success_url = "/rsvp/confirmado"
    template_name = "rsvp/confirmacaohome.html"

    def form_valid(self, form):
        fone, email = (form['fone'].data,
                       form['email'].data)

        fone = phone_validator(fone)
        email = email.lower()

        if email and fone:
            convidado = ConvidadoRSVP.objects.filter(email=email.lower(),
                                                     fone=fone)
        else:
            if email and ConvidadoRSVP.objects.filter(
                    email=email.lower()):
                convidado = ConvidadoRSVP.objects.filter(
                    email=email.lower())
            else:
                convidado = ConvidadoRSVP.objects.filter(fone=fone)

        if convidado:
            convidado = convidado[0]
        else:
            if email and fone:
                convidado, _ = ConvidadoRSVP.objects.get_or_create(
                    email=email, fone=fone)
            else:
                convidado, _ = ConvidadoRSVP.objects.get_or_create(
                    fone=fone)

        return HttpResponseRedirect(convidado.get_absolute_url())


class ConfirmacaoUpdateView(UpdateView):
    model = ConvidadoRSVP
    form_class = ConvidadoRSVPForm
    success_url = "/rsvp/confirmado"

    def get_context_data(self, **kwargs):
        context = super(ConfirmacaoUpdateView, self).get_context_data(**kwargs)
        context['acompanhante_form'] = AcompanhanteRSVPForm
        return context

    def form_valid(self, form):
        primeiro_acesso = self.object.eh_primeiro_acesso
        self.object = form.save(commit=False)
        self.object.eh_primeiro_acesso = False
        self.object.fone = phone_validator(self.object.fone)
        self.object.email = self.object.email.lower()
        self.object.data = timezone.now()
        self.object.contabilizado = False
        self.object.save()

        if not primeiro_acesso:
            email_body = 'RSVP de {0} atualizado para {1}.'.format(
                self.object.nome_completo, self.object.rsvp)
            send_mail('Elaine & Roger - RSVP', email_body,
                      'roger@na-inter.net',
                      ['huogerac@gmail.com', 'lan.galvao@gmail.com'],
                      fail_silently=False)
        else:
            return HttpResponseRedirect(self.object.get_absolute_url())
        return super(ConfirmacaoUpdateView, self).form_valid(form)


class ConfirmacaoAcompanhanteCreateView(CreateView):
    model = AcompanhanteRSVP
    form_class = AcompanhanteRSVPForm

    def form_valid(self, form):
        convidado = get_object_or_404(ConvidadoRSVP,
                                      pk=self.kwargs['convidado_pk'])
        self.object = form.save(commit=False)
        self.object.convidado_rsvp = convidado
        self.object.save()
        return HttpResponseRedirect(
            self.object.convidado_rsvp.get_absolute_url())


class ConfirmacaoAcompanhanteDeleteView(DeleteView):
    model = AcompanhanteRSVP
    form_class = AcompanhanteRSVPForm

    def get_success_url(self):
        convidado = get_object_or_404(ConvidadoRSVP,
                                      pk=self.kwargs['convidado_pk'])
        return convidado.get_absolute_url()


class ListaConvidadosListView(views.LoginRequiredMixin,
                              views.StaffuserRequiredMixin, ListView):
    model = Convidado
    paginate_by = '140'
    context_object_name = 'imoveis_list'

    def get_context_data(self, **kwargs):
        context = super(ListaConvidadosListView,
                        self).get_context_data(**kwargs)
        context['rsvp_convidado'] = ConvidadoRSVP.objects.all().order_by('-data')
        for grupo, descricao in Convidado.GRUPOS:
            total_convidados = Convidado.objects.filter(
                grupo=grupo).count()
            total_acompanhantes = Acompanhante.objects.filter(
                convidado__grupo=grupo, tipo=TIPO_ACOMPANHANTE.adulto).count()
            grupo_str = slugify(grupo)
            semrsvp_convidados = Convidado.objects.filter(
                grupo=grupo, rsvp=RSVP.vazio).count()
            semrsvp_acompanhantes = Acompanhante.objects.filter(
                convidado__grupo=grupo, rsvp=RSVP.vazio,
                tipo=TIPO_ACOMPANHANTE.adulto).count()
            semrsvp = 100
            total = (total_convidados + total_acompanhantes)
            if total > 0:
                semrsvp = (semrsvp_convidados + semrsvp_acompanhantes) * 100 / total
            context["semrsvp_{0}".format(grupo_str)] = semrsvp

        confirmado_noivo = Convidado.objects.filter(
                grupo__icontains="Noivo", rsvp=RSVP.sim).count()
        confirmado_noivo += Acompanhante.objects.filter(
                convidado__grupo__icontains="Noivo",
                rsvp=RSVP.sim, tipo=TIPO_ACOMPANHANTE.adulto).count()
        context["confirmado_noivo"] = confirmado_noivo

        confirmado_noiva = Convidado.objects.filter(
                grupo__icontains="Noiva", rsvp=RSVP.sim).count()
        confirmado_noiva += Acompanhante.objects.filter(
                convidado__grupo__icontains="Noiva",
                rsvp=RSVP.sim, tipo=TIPO_ACOMPANHANTE.adulto).count()
        context["confirmado_noiva"] = confirmado_noiva

        total_convidados = Convidado.objects.all().count()
        total_convidados += Acompanhante.objects.filter(
            tipo=TIPO_ACOMPANHANTE.adulto).count()
        context["total_convidados"] = total_convidados

        sem_rsvp = Convidado.objects.filter(rsvp=RSVP.vazio).count()
        sem_rsvp += Acompanhante.objects.filter(
            tipo=TIPO_ACOMPANHANTE.adulto, rsvp=RSVP.vazio).count()
        context["sem_rsvp"] = sem_rsvp

        rsvp_nao = Convidado.objects.filter(rsvp=RSVP.nao).count()
        rsvp_nao += Acompanhante.objects.filter(
            tipo=TIPO_ACOMPANHANTE.adulto, rsvp=RSVP.nao).count()
        context["rsvp_nao"] = rsvp_nao

        rsvp_sim = Convidado.objects.filter(rsvp=RSVP.sim).count()
        rsvp_sim += Acompanhante.objects.filter(
            tipo=TIPO_ACOMPANHANTE.adulto, rsvp=RSVP.sim).count()
        context["rsvp_sim"] = rsvp_sim

        context["novos"] = ConvidadoRSVP.objects.filter(contabilizado=False)
        return context

    def get_queryset(self, **kwargs):
        queryset = Convidado.objects.all()
        return queryset.order_by('-grupo', 'nome_completo')


class ConvidadoRSVPUpdateView(views.LoginRequiredMixin,
                              views.StaffuserRequiredMixin, UpdateView):
    model = ConvidadoRSVP
    form_class = ListaConvidadoRSVPForm
    success_url = reverse_lazy('rsvp.lista.convidados.list')
    template_name = "rsvp/convidado_form.html"


class ConvidadoUpdateView(views.LoginRequiredMixin,
                          views.StaffuserRequiredMixin, UpdateView):
    model = Convidado
    form_class = ListaConvidadoForm
    success_url = reverse_lazy('rsvp.lista.convidados.list')
    template_name = "rsvp/convidado_form.html"


class AcompanhanteUpdateView(views.LoginRequiredMixin,
                             views.StaffuserRequiredMixin, UpdateView):
    model = Acompanhante
    form_class = ListaAcompanhanteForm
    success_url = reverse_lazy('rsvp.lista.convidados.list')
    template_name = "rsvp/convidado_form.html"

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/templates/rsvp/base_rsvp.html
{% raw %}
{% extends 'themes/default/base.html' %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/templates/rsvp/confirmacaohome.html
{% raw %}
{% extends 'rsvp/base_rsvp.html' %}

{% load static %}
{% load floppyforms %}

{% block extrajs_top %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block content %}

  <!-- Main -->
  <section class="main text-center" id="home" style="height: 26px;">
    <div class="page">
      <div class="wrapper">
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="section-title">Confirmação de presença</h3>
          <div class="section-title-border"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <p class="lead">
          Após nossa cerimônia <abbr title="4 Julho 2015 às 16:45 em São José dos Campos">religiosa</abbr>, ficaremos muito felizes  com sua presença em nossa singela recepção.
          </p>
          <p class="lead">
          Iremos recebê-los no restaurante Azenda com um coquetel para os familiares mais próximos. Como o restaurante conta com um espaço limitado de pessoas, contamos com a sua colaboração confirmando ou não a presença.
          </p>
          <p>
            Por favor, entre com um <strong>TELEFONE</strong> e/ou <strong>EMAIL</strong> válido para que possamos entrar em contato caso necessário.
          </p>
        </div>

        <div class="col-sm-12">

          <form method='post' >{% csrf_token %}
            
            {{ form }}

            <p>
              <br/>
              <button type="submit" class="btn btn-warning btn-lg">
                <i class="fa fa-arrow-right"></i> Continuar
              </button>
            </p>
          </form>

        </div>
        
      </div>
    </div>
  </section>

{% endblock content %}

{% block extrajs_bottom %}
    <script type="text/javascript">

      $(window).load(function () {
        "use strict";
        $('body').delay(350).css({
          'overflow': 'visible'
        });
      });

    </script>
{% endblock extrajs_bottom %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/templates/rsvp/confirmado.html
{% raw %}
{% extends 'rsvp/base_rsvp.html' %}

{% load static %}

{% block content %}

  <section id="about" class="section">
    <div class="container">
      <div class="row">

        <div class="col-xs-12">
          <center>
            <i class="fa fa-heart" style="font-size: 56px" ></i>
            <h2><strong>Muito obrigado! Estamos contando os dias para nos encontrarmos...</strong></h2>
            <h2>Sabemos que emprevistos acontecem, portanto em caso de não comparecimento, pedimos por gentileza que nos avisem com antecedência
            através do mesmo endereço <a href="{% url 'rsvp.confirmacaohome' %}">(http://{{ DJ_CASAMENTO_SERVER }}/confirmacao/)</a></h2>
            <h1 class="heading">{{ DJ_CASAMENTO_DE_UM_LADO }} <span style="color: yellow;">&</span> {{ DJ_CASAMENTO_DO_OUTRO }}</h1>
            <p>
              <a class="btn btn-default btn-lg" href="{% url 'core.showhome' %}">Ir para página principal</a>
            </p>
          </center>

        </div>

      </div>
    </div>
  </section>

{% endblock %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/templates/rsvp/convidado_form.html
{% raw %}
{% extends 'rsvp/base_rsvp.html' %}

{% load static %}
{% load floppyforms %}

{% block extrajs_top %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}

  <!-- Main -->
  <section class="main text-center" id="home" style="height: 26px;">
    <div class="page">
      <div class="wrapper">
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <div class="row">

        <div class="col-sm-12">

          <form method='post' enctype="multipart/form-data">{% csrf_token %}

            {{ form}}

            <div class="row">

              <div class="col-xs-4">
                <div class="pull-right">
                  <button type="submit" class="btn btn-warning btn-lg">
                    <i class="fa fa-thumbs-o-up"></i> Salvar
                  </button>
                </div>
              </div>
            </div>

          </form>

        </div>

      </div>
    </div>
  </section>

{% endblock %}

{% block extrajs_bottom %}
    <script type="text/javascript">

      $(window).load(function () {
        "use strict";
        $('body').delay(350).css({
          'overflow': 'visible'
        });

      });

    </script>
{% endblock extrajs_bottom %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/rsvp/templates/rsvp/convidadorsvp_form.html
{% raw %}
{% extends 'rsvp/base_rsvp.html' %}

{% load static %}
{% load floppyforms %}

{% block extrajs_top %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}

  <!-- Main -->
  <section class="main text-center" id="home" style="height: 26px;">
    <div class="page">
      <div class="wrapper">
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <div class="row">

        <div class="col-sm-12">

          <form method='post' enctype="multipart/form-data">{% csrf_token %}

            {% if object.eh_primeiro_acesso %}
              <input type="hidden" name="primeiro_acesso" id="id_primeiro_acesso">
            {% endif %}

            <div class="row">
              <div class="col-xs-8">
                <p><small>4 Julho 2015 às 16:45 em São José dos Campos</small></p>
              </div>
              <div class="col-xs-4">
                <div class="pull-right">
                  <button type="submit" class="btn btn-warning btn-lg">
                    {% if object.eh_primeiro_acesso %}
                      <i class="fa fa-arrow-right"></i> Continuar
                    {% else %}
                      <i class="fa fa-thumbs-o-up"></i> OK
                    {% endif %}
                  </button>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-8">{% formrow form.nome_completo %}</div>
              <div class="col-xs-4">{% formrow form.rsvp %}</div>
            </div>

            <div class="row">
              <div class="col-xs-5">{% formrow form.fone %}</div>
              <div class="col-xs-7">{% formrow form.email %}</div>
            </div>
          </form>

          {% if not object.eh_primeiro_acesso %}
          <div id="acompanhantes">
            <h4>Acompanhante(s)</h4>
            <table class="table table-striped">
              <tbody>
              {% for acompanhante in object.acompanhantes.all %}
                <tr>
                  <td>1</td>
                  <td>{{ acompanhante.tipo_verbose }}</td>
                  <td>{{ acompanhante.nome }}</td>
                  <td>
                    <small>
                      <form method="POST" action="{% url 'rsvp.confirmacao.convidado.delete' acompanhante.id object.id %}">{% csrf_token %}
                        <button type="submit" class="btn btn-default">
                          <i class="fa fa-trash"></i> Remover
                        </button>
                      </form>
                    </small>
                  </td>
                </tr>
              {% endfor %}

              <form method='post' action="{% url 'rsvp.confirmacao.convidado.create' object.id %}" enctype="multipart/form-data">{% csrf_token %}
                <tr>
                  <td>1</td>
                  <td>{% formrow acompanhante_form.tipo %}</td>
                  <td>{% formrow acompanhante_form.nome %}</td>
                  <td><br/> 
                    <button type="submit" class="btn btn-lg btn-success">
                      <i class="fa fa-plus"></i> Adicionar
                    </button>
                  </td>
                </tr>
              </form>

              </tbody>
            </table>
          </div>
          <center>
          <p><strong>IMPORTANTE:</strong> Haverá uma lista de entrada no restaurante, portanto recomendamos a verificação do nome do convidado e do(s) acompanhante(s).</p>            
          </center>
          {% endif %}

        </div>

      </div>
    </div>
  </section>

{% endblock %}

{% block extrajs_bottom %}
    <script type="text/javascript">

      $(window).load(function () {
        "use strict";
        $('body').delay(350).css({
          'overflow': 'visible'
        });

        if ( $( "#id_primeiro_acesso" ).length ) {
          $( "#id_nome_completo" ).focus();
        } else {
          $( "#id_nome_completo" ).attr("readonly", true);
          $( "#id_fone" ).attr("readonly", true);
          $( "#id_rsvp" ).focus();
        }

        $("#id_rsvp").on('change', function() {
          var rsvp = $(this).val();
          if (rsvp == 'sim') {
            $( "#acompanhantes" ).show();
            $( "#id_rsvp" ).css("background-color", "#5CB85C");
          } else {
            $( "#acompanhantes" ).hide();
            $( "#id_rsvp" ).css("background-color", "#F24D4D");
          }
        });

        $("#id_rsvp").change();

      });

    </script>
{% endblock extrajs_bottom %}
{% endraw %}