{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .views import ShowHomeView, SaveTheDateView, ConfirmacaoRedirectView
from .forms import LoginForm


urlpatterns = patterns('',  # noqa

    url(r'^confirmacao/$', ConfirmacaoRedirectView.as_view(),
        name='core.confirmacao'),
    url(r'^confirmacao$',
        ConfirmacaoRedirectView.as_view(),),

    url(r'^$', ShowHomeView.as_view(),
        name='core.showhome'),

    url(r'^save-the-date/$',
        SaveTheDateView.as_view(), name='core.savethedate'),

    url(r'^dicasdehoteis/$',
        TemplateView.as_view(template_name="core/dicasdehoteis.html"),
        name='core.dicasdehoteis'),

    url(r'^apps/$',
        TemplateView.as_view(template_name="core/apps.html"),
        name='core.apps'),

    url(r'^agradecimentopresente/$',
        TemplateView.as_view(template_name="core/agradecimento_presente.html"),
        name='core.agradecimentopresente'),

    url(r'^cerimoniareligiosa/$',
        TemplateView.as_view(template_name="core/cerimoniareligiosa.html"),
        name='core.cerimoniareligiosa'),

    url(r'^salaodebeleza/$',
        TemplateView.as_view(template_name="core/salaodebeleza.html"),
        name='core.salaodebeleza'),

    url(r'^restaurante/$',
        TemplateView.as_view(template_name="core/restaurante.html"),
        name='core.restaurante'),

    url(r'^avisoconfirmacao/$',
        TemplateView.as_view(template_name="core/avisoconfirmacao.html"),
        name='core.avisoconfirmacao'),

    # login
    url(r'^auth/$',
        auth_views.login, {'template_name': 'core/login.html',
                           'authentication_form': LoginForm},
        name='url_login_auth'),

)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/fornecedores/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import (FornecedoresListView, )


urlpatterns = patterns('',  # noqa

    url(r'^$',
        FornecedoresListView.as_view(),
        name='fornecedores.lista'),

)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/fornecedores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models


@python_2_unicode_compatible
class Fornecedor(models.Model):
    nome = models.CharField(
        _('Fornecedor'), max_length=128, default='')
    categoria = models.CharField(
        _('Categoria (Buffet, Som etc..)'), blank=True, default='',
        max_length=128)
    contato = models.CharField(
        _('Nome do Contato'), blank=True, default='',
        max_length=128)
    email = models.EmailField(
        _('e-mail'), max_length=128, blank=True)
    fone = models.CharField(
        _('Fone'), max_length=32, default='', blank=True)
    fone2 = models.CharField(
        _('Fone (alternativo)'), max_length=32, default='', blank=True)
    site = models.URLField(
        _('Site'), max_length=256, blank=True)
    notas = models.TextField(
        _('Notas'), blank=True, default='')
    endereco = models.TextField(
        _('Endereço'), blank=True, default='')

    class Meta:
        verbose_name = _("Fornecedor")
        ordering = ('nome', )

    def __str__(self):
        return "{0} ({1})".format(self.nome, self.categoria)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/fornecedores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import division

from django.views.generic import ListView

from .models import Fornecedor


class FornecedoresListView(ListView):
    model = Fornecedor
    paginate_by = '100'

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/fornecedores/templates/fornecedores/fornecedor_list.html
{% raw %}
{% extends 'themes/default/base.html' %}

{% load static %}

{% block content %}

  <section id="about" class="section">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="section-title">Lista de fornecedores</h3>
          <div class="section-title-border"></div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <table class="table table-condensed table-hover">
            <thead>
              <tr>
                <th>Fornecedor</th>
                <th></th>
                <th>Contato</th>
                <th>Endereço</th>
                <th>Notas</th>
              </tr>
            </thead>
            <tbody>
            {% for fornecedor in object_list %}
              <tr>
                <td>{{ fornecedor.nome }}<br/>
                    <small><a href="{{ fornecedor.site }}">{{ fornecedor.site }}</a></small>
                </td>
                <td>{{ fornecedor.categoria }}</td>
                <td>{{ fornecedor.contato }}<br/>
                    {{ fornecedor.email }}<br/>
                    {{ fornecedor.fone }} {{ fornecedor.fone2 }}
                    <br/>
                </td>
                <td><small>{{ fornecedor.endereco }}</small></td>
                <td>
                  <small>{{ fornecedor.notas }}</small>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>

      </div>

      <div class="row">
        <div class="col-xs-12">
          <center>
            <p><br/></p>
            <p>
              <a class="btn btn-default btn-lg" href="{% url 'core.showhome' %}">Ir para página principal</a>
              <a class="btn btn-warning btn-lg" href="{% url 'roteiros.lista' %}">Roteiros</a>
            </p>
          </center>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block extrajs_bottom %}

{% endblock extrajs_bottom %}
{% endraw %}