{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .views import ShowHomeView, SaveTheDateView, ConfirmacaoRedirectView
from .forms import LoginForm


urlpatterns = patterns('',  # noqa

    url(r'^confirmacao/$', ConfirmacaoRedirectView.as_view(),
        name='core.confirmacao'),
    url(r'^confirmacao$',
        ConfirmacaoRedirectView.as_view(),),

    url(r'^$', ShowHomeView.as_view(),
        name='core.showhome'),

    url(r'^save-the-date/$',
        SaveTheDateView.as_view(), name='core.savethedate'),

    url(r'^dicasdehoteis/$',
        TemplateView.as_view(template_name="core/dicasdehoteis.html"),
        name='core.dicasdehoteis'),

    url(r'^apps/$',
        TemplateView.as_view(template_name="core/apps.html"),
        name='core.apps'),

    url(r'^agradecimentopresente/$',
        TemplateView.as_view(template_name="core/agradecimento_presente.html"),
        name='core.agradecimentopresente'),

    url(r'^cerimoniareligiosa/$',
        TemplateView.as_view(template_name="core/cerimoniareligiosa.html"),
        name='core.cerimoniareligiosa'),

    url(r'^salaodebeleza/$',
        TemplateView.as_view(template_name="core/salaodebeleza.html"),
        name='core.salaodebeleza'),

    url(r'^restaurante/$',
        TemplateView.as_view(template_name="core/restaurante.html"),
        name='core.restaurante'),

    url(r'^avisoconfirmacao/$',
        TemplateView.as_view(template_name="core/avisoconfirmacao.html"),
        name='core.avisoconfirmacao'),

    # login
    url(r'^auth/$',
        auth_views.login, {'template_name': 'core/login.html',
                           'authentication_form': LoginForm},
        name='url_login_auth'),

)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import (PaginaPrincipalListView,
                    IntencaoDePresenteCreateView,
                    IntencaoDePresenteConfirmacaoView)


urlpatterns = patterns('',  # noqa

    url(r'^$',
        PaginaPrincipalListView.as_view(),
        name='listapresentes.home'),

    url(r'^comprar-presente/(?P<pk>\d+)/$',
        IntencaoDePresenteCreateView.as_view(),
        name='listapresentes.intencao.create'),

    url(r'^comprar-presente/confirmacao/(?P<pk>\d+)/$',
        IntencaoDePresenteConfirmacaoView.as_view(),
        name='listapresentes.intencao.confirmacao'),

)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division

from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

from model_utils import Choices


@python_2_unicode_compatible
class Presente(models.Model):
    titulo = models.CharField(
        _('Título'), blank=True, max_length=128, default='')
    descricao = models.TextField(
        _('Descrição do presente'), blank=True, default='')
    imagem = models.ImageField(
        _('imagem'), upload_to='presentes', blank=True, default='')
    valor = models.DecimalField(
        _('Valor'), max_digits=12, decimal_places=2, default=0.00)

    class Meta:
        verbose_name = _("Presente")
        ordering = ('valor', )

    def __str__(self):
        return "{0} (R${1})".format(self.titulo, self.valor)


@python_2_unicode_compatible
class IntencaoDePresente(models.Model):
    BANCO = Choices(('bradesco', _('Bradesco')),
                    ('itau', _('Itaú')),
                    ('santander', _('Santander')), )
    data = models.DateTimeField(auto_now_add=True, editable=False)
    presente = models.ForeignKey(Presente, verbose_name=_('presente'))
    nome = models.CharField(_('Seu nome'), default='', max_length=128)
    email = models.EmailField(_('e-mail'), max_length=128)
    banco = models.CharField(_('Transferir para o banco'), choices=BANCO,
                             default=BANCO.itau, max_length=16)
    mensagem = models.TextField(
        _('Mensagem para o casal'), blank=True, default='')
    valor = models.DecimalField(
        _('Valor'), max_digits=12, decimal_places=2, default=0.00)
    pagamento_ok = models.BooleanField(default=False)
    saque_ok = models.BooleanField(default=False)
    agradecimento_ok = models.BooleanField(default=False)
    foto_agradecimento_ok = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Intenção de Presente")
        ordering = ('pagamento_ok', 'banco', 'saque_ok',
                    'agradecimento_ok', '-id', )

    def __str__(self):
        ok = " [OK]" if self.pagamento_ok else " --> [VER CONTA]"
        ok += " [$$$acado] " if self.saque_ok else ""
        ok += " [Tks] " if self.agradecimento_ok else ""
        return "{0} ({1},{2}) - {3}".format(
            self.nome, self.valor, self.banco, ok)

    @property
    def centavos(self):
        return float(str(self.valor-int(self.valor))[1:])

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.utils.translation import ugettext_lazy as _

import floppyforms.__future__ as forms
from floppyforms.widgets import EmailInput, TextInput

from .models import IntencaoDePresente


class IntencaoDePresenteForm(forms.ModelForm):

    class Meta:
        model = IntencaoDePresente
        fields = ('presente', 'nome', 'email', 'banco', 'mensagem', )
        help_texts = {
            'email': 'Informe um email para enviarmos a confirmação.',
        }

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import division

from random import randint

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

from .models import Presente, IntencaoDePresente
from .forms import IntencaoDePresenteForm


class PaginaPrincipalListView(ListView):
    model = Presente
    paginate_by = '100'
    context_object_name = 'presente_list'


class IntencaoDePresenteCreateView(CreateView):
    model = IntencaoDePresente
    form_class = IntencaoDePresenteForm

    def get_initial(self):
        presente = get_object_or_404(Presente, pk=self.kwargs['pk'])
        initial = {
            'presente': presente,
        }
        return initial

    def form_valid(self, form):
        self.object = form.save(commit=False)
        centavos = randint(1, 99) / 100
        self.object.valor += centavos + float(self.object.presente.valor)
        self.object.save()
        url = reverse("listapresentes.intencao.confirmacao",
                      kwargs={'pk': self.object.id})
        email_body = '{0} teve uma intenção de presente {1} ({2}, {3})'.format(
            self.object.nome, self.object.presente, self.object.valor, self.object.banco)

        send_mail('Elaine & Roger - PRESENTE', email_body,
                  'roger@na-inter.net',
                  ['huogerac@gmail.com', 'lan.galvao@gmail.com'],
                  fail_silently=False)

        return HttpResponseRedirect(url)


class IntencaoDePresenteConfirmacaoView(UpdateView):
    model = IntencaoDePresente
    form_class = IntencaoDePresenteForm
    template_name = "listapresentes/intencaodepresente_confirmacao.html"

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/templates/listapresentes/base_listapresentes.html
{% raw %}
{% extends 'themes/default/base.html' %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/templates/listapresentes/intencaodepresente_confirmacao.html
{% raw %}
{% extends 'listapresentes/base_listapresentes.html' %}

{% load static %}
{% load floppyforms %}

{% block extrajs_top %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}

  <!-- Main -->
  <section class="main text-center" id="home" style="height: 26px;">
    <div class="page">
      <div class="wrapper">
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <div class="row">

        <div class="col-xs-4">
          <h1>Comprar presente para Elaine & Roger</h1>
        </div>
        <div class="col-xs-8">

          <h3><strong>{{ object.nome }}</strong>,</h3>
          <h3>
          Por favor, transferir o valor de <small>R$</small><strong>{{ object.valor }}</strong> para uma das nossas contas bancárias listada abaixo:
          </h3>
          
          <h2><i class="fa fa-angle-right"></i> Banco Itaú</h2>
          <h4><small>Favorecido:</small> Roger de Almeida Camargo - <small>CPF:</small> 302.104.228-74</h4>
          <h4><small>ag:</small> 2954 <small>cc:</small> 60237-7 </h4>

          <center><p>OU</p></center>
          <h2><i class="fa fa-angle-right"></i> Banco Bradesco</h2>
          <h4><small>Favorecido:</small> Roger de Almeida Camargo - <small>CPF:</small> 302.104.228-74</h4>
          <h4><small>ag:</small> 1382 <small>cc:</small> 0127308-6 </h4>

          <center><p>OU</p></center>
          <h2><i class="fa fa-angle-right"></i> Banco Santander</h2>
          <h4><small>Favorecido:</small> Elaine Santos Galvão - <small>CPF:</small>318.385.498-89</h4>
          <h4><small>ag:</small> 4334 <small>cc:</small> 01059120-6 </h4>
          <br/>
          <h3>Muito obrigado.</h3>
          <br/>
          <p>Observações:</p>
          <p>- Os <strong>{{ object.centavos }}</strong> centavos do valor transferido é como iremos identificar a sua transferência.</p>

        </div>
        <div class="col-xs-12">
          <center>
            <p>
              <a class="btn btn-default btn-lg" href="{% url 'core.showhome' %}">Ir para página principal</a>
            </p>            
          </center>
        </div>

      </div>
    </div>
  </section>

{% endblock %}

{% block extrajs_bottom %}

{% endblock extrajs_bottom %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/templates/listapresentes/intencaodepresente_form.html
{% raw %}
{% extends 'listapresentes/base_listapresentes.html' %}

{% load static %}
{% load floppyforms %}

{% block extrajs_top %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}

  <!-- Main -->
  <section class="main text-center" id="home" style="height: 26px;">
    <div class="page">
      <div class="wrapper">
      </div>
    </div>
  </section>

  <section id="about" class="section">
    <div class="container">
      <div class="row">

        <div class="col-xs-5">
          <h1>Comprar presente para Elaine & Roger</h1>
          <p>Assim que você confirmar suas informações, iremos te informar nossa conta bancária para transferência.
          </p>
          <p>Assim iremos utilizar esse valor para comprar o presente!</p>
          <p>Obrigado.</p>

        </div>
        <div class="col-xs-7">

          <form method='post' enctype="multipart/form-data">{% csrf_token %}

            {{ form }}

            <button type="submit" class="btn btn-warning btn-lg">
              <i class="fa fa-thumbs-o-up"></i> CONFIRMAR
            </button>

          </form>

        </div>

      </div>

      <div class="row">
        <div class="col-xs-12">
          <center>
            <p><br/></p>
            <p>
              <a class="btn btn-default btn-lg" href="{% url 'listapresentes.home' %}">Voltar para lista</a>
              <a class="btn btn-default btn-lg" href="{% url 'core.showhome' %}">Ir para página principal</a>
            </p>
          </center>
        </div>
      </div>

    </div>
  </section>

{% endblock %}

{% block extrajs_bottom %}
    <script type="text/javascript">

      $( "#id_nome" ).focus();

    </script>
{% endblock extrajs_bottom %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/listapresentes/templates/listapresentes/presente_list.html
{% raw %}
{% extends 'listapresentes/base_listapresentes.html' %}

{% load static %}
{% load floppyforms %}

{% block content %}

  <section id="about" class="section">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="section-title">Lista de presentes</h3>
          <div class="section-title-border"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
            <center>
              <p class="lead">
                <strong>pre.sen.te</strong>
                <small>1</small> Que existe ou sucede no momento de que se fala; atual. 
                <small>2</small> Diz-se da pessoa ou coisa que momento diante dos olhos
                <small>3</small> Que assiste em pessoa: Presente ao ato. 
                <small>4</small> Que está a ponto de se realizar; iminente. 
                <small>5</small> Diz-se do tempo que exprime ação que está sendo feita;
                <small>6</small> O tempo presente; o tempo atual.
                <small>7</small> Tempo que nos modos verbais exprime a ideia do momento em que se fala. 
                <small>8</small> Brinde, dádiva, mimo, oferenda, oferta.              
              </p>
            </center>
          <p class="lead">
          E apenas pela definição da palavra, sua presença e o seu tempo dedicados em celebrar conosco a nossa felicidade, ja seriam mais do que os nossos melhores presentes.
          </p>
          <h1><strong>Cotas para a lua de mel</strong></h1>
          <p>
            Nos iremos ficar de pernas pro ar alguns dias em Paraty-RJ, cidade histórica, cheia de vida e poesia, que de tão perto da gente ainda não conhecemos. Para aqueles que querem contribuir com nossa lua-de-mel, seguem algumas sugestões de passeios que queremos fazer por lá:
          </p>
        </div>
      </div>

      <div class="row">
        {% for presente in presente_list %}
          <div class="col-sm-4">
            <p>
              <img width="100%" src="{{ presente.imagem.url }}">
            </p>
            <h2><strong>{{ presente.titulo }}</strong></h2>
            <h3>
              <span style="font-size: 20px;">R$</span><strong>{{ presente.valor }}</strong>
              <a href="{% url 'listapresentes.intencao.create' presente.id %}" class="btn btn-success"><i class="fa fa-gift"></i> Comprar presente</a>
            </h3>
            <p><small>{{ presente.descricao }}</small></p>
          </div>

          {% if forloop.counter|divisibleby:3 %}
            <div class="clearfix visible-lg-block"></div>
          {% endif %}

        {% endfor %}
      </div>

      <div class="row">
        <div class="col-xs-12">
          <center>
            <p><br/></p>
            <p>
              <a class="btn btn-default btn-lg" href="{% url 'core.showhome' %}">Ir para página principal</a>
            </p>
          </center>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block extrajs_bottom %}

{% endblock extrajs_bottom %}
{% endraw %}